about:
  avatar: https://source.geniucker.top/avatar.webp
  name: "Geniucker"
  intro: "This is Geniucker's Blog"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/geniucker', tip: 'GitHub' }
    - { class: 'iconfont icon-mail', link: 'mailto:me@geniucker.top', tip: 'Email' }
index:
  slogan:
    enable: true
    text: 这里是Geniucker的博客，可能有是写笔记和随笔


favicon: https://source.geniucker.top/logo/logo.svg
navbar:
  blog_title: Geniucker's Blog
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }


post:
  math:
    # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `math: true`
    # If you want to use math on the custom page, you need to set `math: true` in Front-matter
    enable: true

    # 开启后，只有在文章 Front-matter 里指定 `math: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    # If true, only set `math: true` in Front-matter will enable math, to load faster when the page does not contain math
    specific: true

    # Options: mathjax | katex
    engine: mathjax
  comments:
    enable: true
    type: gitalk
gitalk:
  clientID: e2869988ac40d1373f3f
  clientSecret: 6ce3ad433a0c2ff750a5c1fd68bf322c0a96532f
  repo: gitalk-commnet 
  owner: Geniucker
  admin:
    - Geniucker
  option:


footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"